name: Deploy DotNet project to Azure Function App

on:
  [push]
 
env:

  AZURE_FUNCTIONAPP_NAME: 'Github-action-test' # Azure Function App name
  DOTNET_VERSION: '8.0.x'                   # .NET version to use
 
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup .NET Environment
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
 
    - name: Build Project
      run: |
        dotnet build --configuration Release --output ./output
 
    - name: Deploy to Azure Function App
      uses: Azure/functions-action@v1
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: './output'
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}